import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Wrapper from "@/components/wrapper/Wrapper";

export const metadata = {
  title: "Internshala-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
