"use client";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";

// export const metadata = {
//   title: "Student | HomePage",
//   description: "Generated by create next app",
// };

const page = () => {
  return (
    <div>
      Authenticated studnet page <br />
    </div>
  );
};

export default page;
