"use client";
import { asyncsignoutstudent } from "@/store/Actions/studentActions";
import Link from "next/link";
import { useRouter } from "next/navigation";
import React, { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";

// export const metadata = {
//   title: "Student | HomePage",
//   description: "Generated by create next app",
// };

const page = () => {
  const dispatch = useDispatch();
  const signoutHandler = () => {
    dispatch(asyncsignoutstudent());
  };

  const { isAuthenticated } = useSelector((state) => state.studentReducer);
  const router = useRouter();
  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/");
    }
  }, [!isAuthenticated]);
  return (
    <div>
      Authenticated studnet page <br />
      <button onClick={signoutHandler}>signout</button>
    </div>
  );
};

export default page;
