import React from "react";

export const metadata = {
  title: "Student | HomePage",
  description: "Generated by create next app",
};
const page = () => {
  return <div>Authenticated studnet page</div>;
};

export default page;
